version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    ports:
      - "8080:80"

    volumes:
      - .:/app/

    links:
      - php
      - db
    networks:
      - pg-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    volumes:
      - .:/app/

    networks:
      - pg-network

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}


    networks:
      - pg-network


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

    networks:
      - pg-network

volumes:
  pgadmin-data:

networks:
  pg-network:

